Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |v|
      v.gui = true
    end

    config.vm.define "ubuntu" do |ubuntu|
       ubuntu.vm.box = "generic/ubuntu2204"
       ubuntu.vm.network "private_network", type: "dhcp"
       ubuntu.vm.synced_folder '.', '/vagrant', disabled: false
    end

    config.vm.define "win2019" do |win2019|
       win2019.vm.box = "StefanScherer/windows_2019"
       win2019.vm.network "private_network", type: "dhcp"
       win2019.vm.synced_folder '.', '/vagrant', disabled: false
    end
end
